# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcaf75d5d0a4cc12234fffe22bd26ddf96a9924f15e32c5556d4b3af19a0c39b37ef9ac749e73d74d9e483e20b20baa94217ffb663ff9091f958e348ec653b8

test:
  secret_key_base: 995124ea39fb3450413babf4f7990b98cdef27dd633085a10dc55f78088007ff206cd27ab6a7cd14aeddeec6618baee813ee98908b12d5a36cf50f498e15d55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
